import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Event App",
  description: "Generated by create Event app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">               
        {children}
      </body>
    </html>
  );
}